---
# Base role
# Silverstripe role
###################

# Where our site goes on the vm
mrwf_root: /var/www/httpdocs
mrwf_mysql_database: ss_millroadwf
mrwf_mysql_user: root
mrwf_mysql_password: root

# Instructions for the mysql role
mysql_databases: [ ss_millroadwf ]
mysql_root_username: root
mysql_root_db_pass: root

# Instructions for the apache role
apache_listen_port: 80
apache_vhosts:
   - {servername: "local.millroadwinterfair.org", documentroot: "{{ mrwf_root }}"}
