---
- hosts: all
  gather_facts: yes
  become: True
  roles:
    - { role: iroquoisorg.php5 }
    - { role: oefenweb.composer }
    - { role: geerlingguy.apache }
    - { role: iroquoisorg.mysql }
    - { role: silverstripe }
